name: Bundle JavaScript

on: 
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create dist folder and add files
      run: |
        if [ ! -d "dist" ]; then 
        mkdir dist
        echo "Cartella autogenerata tramite action" > dist/notes.txt
        fi
    - name: Overwrite .gitignore
      run: |
        echo "node_modules/" > .gitignore

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Bundle JavaScript
      run: |
        npx webpack --config webpack.config.js

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Commit automatico da GitHub Actions"

    - name: Push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push https://x-access-token:${GH_TOKEN}@github.com/francescoct/hackernews.git HEAD:master

    - name: Ripristino .gitignore
      run: |
        echo "node_modules/" > .gitignore
        echo "dist/" >> .gitignore

    - name: Commit final changes
      run: |
        git add .
        git commit -m "Commit automatico da GitHub Actions"

    - name: Push final changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git push https://x-access-token:${GH_TOKEN}@github.com/francescoct/hackernews.git HEAD:master

    - name: Upload bundled files
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/