name: Bundle JavaScript

on: 
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create dist folder and add files
      run: |
        mkdir dist
        echo "Cartella autogenerata tramite action" > dist/notes.txt

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Bundle JavaScript
      run: |
        npx webpack --config webpack.config.js

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Add dist folder with files"
        git push
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload bundled files
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
  # # gestione download
  # deploy:
    # runs-on: ubuntu-latest
    # needs: build
    # steps:
    #   - name: Download Artifact
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: dist
    #       path: artifact
    #   - name: Display structure of downloaded files
    #     run: ls -R artifact